# Generated by Django 4.1.3 on 2022-11-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='date_releases',
            new_name='date_released',
        ),
    ]
